### ISSUE TITLE
add get methods to device profile import

### ISSUE THREAD

**Issue by bwJuniper** [Juniper/apstra-go-sdk#321]
will we be able to use Update and Read in the CRUD considering we are "importing" the device profile? We certainly will need to read it so i will start there.

**Comment by chrismarget-j** [comment]
We'll need to implement the whole `resource.Resource` interface (CRUD methods + `Metadata()` and `Schema()`), but we can structure things so that `Update()` is never invoked.

What are the inputs here, just `blueprint_id` and `device_profile_id`? If so, mark 'em both with the `RequiresReplace` plan modifier, and `Update()` will never run. It will need to be defined to satisfy the interface, but can be an empty resource.

**Comment by chrismarget-j** [comment]
FWIW, I don't think this one gets a data source.

**Comment by bwJuniper** [comment]
Agree. We can work on this I have a good framework that just needs review/tweaking.

**Comment by bwJuniper** [comment]
Turns out we didnt need a branch or changes.  Everything was done in the Provider.
